# Generated by Django 3.2.2 on 2021-05-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='photos/products')),
                ('image2', models.ImageField(upload_to='photos/products')),
                ('image3', models.ImageField(upload_to='photos/products')),
                ('image4', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('strap_colour', models.CharField(max_length=30)),
                ('water_resistance', models.CharField(max_length=30)),
                ('analogue_or_digital', models.CharField(max_length=30)),
                ('glass', models.CharField(max_length=30)),
                ('strap_type', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
