# Generated by Django 3.2.2 on 2021-05-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=25, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_upto', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(blank=True, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=25, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_upto', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
