# Generated by Django 3.2.2 on 2021-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
