# Generated by Django 3.2.2 on 2021-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210524_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
