# Generated by Django 3.2.2 on 2021-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_categoryoffer_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
