# Generated by Django 3.2.2 on 2021-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productoffer_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='off_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='off_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
