# Generated by Django 3.2.2 on 2021-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210524_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_upto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_upto',
            field=models.DateField(),
        ),
    ]
