# Generated by Django 3.2.2 on 2021-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210524_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
