# Generated by Django 3.2.2 on 2021-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
