# Generated by Django 3.2.2 on 2021-05-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_couponcode_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='price',
            new_name='off_price',
        ),
    ]
