# Generated by Django 3.2.2 on 2021-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_couponcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
