# Generated by Django 3.2.2 on 2021-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=6, unique=True)),
                ('off_price', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_upto', models.DateField()),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
