# Generated by Django 3.2.2 on 2021-05-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantirt',
            new_name='quantity',
        ),
    ]
