# Generated by Django 3.2.2 on 2021-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210523_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referal',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
