# Generated by Django 3.2.2 on 2021-05-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_referal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='referal',
            new_name='referral',
        ),
    ]
