# Generated by Django 3.2.2 on 2021-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_images/default.jpeg', null=True, upload_to='profile_images'),
        ),
    ]
