# Generated by Django 3.2.2 on 2021-05-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('Delivered', 'delivered')], default='pending', max_length=100),
        ),
    ]
