# Generated by Django 3.2.2 on 2021-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('cancelled', 'cancelled')], default='pending', max_length=100),
        ),
    ]
