# Generated by Django 3.2.2 on 2021-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
