# Generated by Django 3.2.2 on 2021-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='new', max_length=20),
        ),
    ]
