# Generated by Django 3.2.2 on 2021-05-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210516_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='paid', max_length=100),
        ),
    ]
