# Generated by Django 3.2.2 on 2021-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210520_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='Order placed', max_length=20),
        ),
    ]
